version: '2'

services:
  drone-server:
    image: 'drone/drone:1.2.1'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/drone:/data'
    env_file:
      - ./drone.env
    environment:
      - DRONE_SERVER_HOST=localhost
      # Variables below set via drone.env file
      # - DRONE_GITHUB_CLIENT_ID=
      # - DRONE_GITHUB_CLIENT_SECRET=
      # - DRONE_RPC_SECRET=
    ports:
      - '80:80'
      - '443:443'
    restart: always
    container_name: drone

  drone-agent:
    image: drone/agent:1.2.1
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_RPC_SERVER=drone-server:9000
      # Variables below set via drone.env file
      # - DRONE_RPC_SECRET=
